site_name: ''
repo_url: https://github.com/OSIPI/pypi

theme:
  name: material
  logo: assets/osipiImgs/OSIPI_logo.png
  favicon: assets/osipiImgs/OSIPI_logo_only_square.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - tables
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - toc.follow

  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - open-in-new-tab
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
  - gallery:
      examples_dirs: docs/examples
      gallery_dirs: docs/generated/gallery

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OSIPI
    - icon: fontawesome/brands/slack
      link: https://app.slack.com/client/TFGVCE9HS

extra_css:
    - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Installation: user-guide/install.md
      - Simulating data:
          - Overview: user-guide/simulate.md
          - Simulate: user-guide/gen_aif.md
      - Fitting data:
          - Overview: user-guide/fitting.md
          - Fit: user-guide/fit_tissue.md

  - About: about/index.md
  - Developer Guide: contribution/index.md
  - References:
      - references/index.md
      - Index:
          - references/models/index.md
          - AIF models:
              - references/models/aif_models/index.md
              - osipi.aif_parker: references/models/aif_models/aif_parker.md
              - osipi.aif_georgiou: references/models/aif_models/aif_georgiou.md
              - osipi.aif_weinmann: references/models/aif_models/aif_weinmann.md
          - Tissue models :
              - references/models/tissue_models/index.md
              - osipi.tofts: references/models/tissue_models/tofts.md
              - osipi.extended_tofts: references/models/tissue_models/extended_tofts.md

  - Examples: generated/gallery


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde